
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

jcihitachi_tw:
  email: kellnfan@gmail.com
  password: You-5574747
  devices:
    - DEVICE_A_NAME
    - DEVICE_B_NAME
